environments:
  - name: Test-env

agents:
  - name: admin
    resources: [docker]
    environment_variables:
      GOCD_AGENT_WORK_DIR: "C:\\Program Files (x86)\\Go Agent"
      DOCKER_HOST: "tcp://docker:2375"
    hostname: 127.0.0.1
    operating_system: Windows 10
    agent_state: Idle
    free_space: "857.36 GB"

pipelines:
  - name: GoCDPipeline
    group: my_pipeline_group
    label_template: '${COUNT}'
    materials:
      - git:
          url: https://github.com/htetgit/My-App-Demo.git
          branch: main
    stages:
      - name: Build
        jobs:
          - name: Compile
            agent: admin
            tasks:
              - exec:
                  command: go
                  arguments: ["build", "-o", "main.exe", "."]
                  working_directory: "."
      # Add more stages if needed
