pipelines:
  hello-world-pipeline:
    group: hello-world-group
    environment_variables:
      DOCKER_USERNAME: "hym101"
      DOCKER_PASSWORD: "!@#123456"
    materials:
      - git:
          url: https://github.com/htetgit/App-Test.git
    stages:
      - build:
          jobs:
            build-docker-image:
              tasks:
                - exec:
                    command: echo
                    arguments: ["Building Docker image..."]
                - exec:
                    command: docker
                    arguments: ["build", "-t", "hym101/testapp/hello-world:latest", "."]
                - exec:
                    command: echo
                    arguments: ["Pushing Docker image to registry..."]
                - exec:
                    command: docker
                    arguments: ["login", "-u", "hym101", "-p", "!@#123456"]
                - exec:
                    command: docker
                    arguments: ["push", "hym101/testapp/hello-world:latest"]
