environments:
  - name: Test-env

agents:
  - name: admin
    resources: [docker]
    environment_variables:
      GOCD_AGENT_WORK_DIR: "C:\\Program Files (x86)\\Go Agent"
      DOCKER_HOST: "tcp://docker:2375"
      DOCKER_USERNAME: "hym101"  # Set your DockerHub username
      DOCKER_PASSWORD: "!@#123456"

    hostname: 127.0.0.1
    operating_system: Windows 10
    agent_state: Idle
    free_space: "857.36 GB"

pipelines:
  - name: GoCDPipeline
    group: my_pipeline_group
    label_template: '${COUNT}'
    materials:
      - git:
          url: https://github.com/htetgit/My-App-Demo.git
          branch: main
    stages:
      - name: Build
        jobs:
          - name: Compile
            agent: admin
            tasks:
              - exec:
                  command: go
                  arguments: ["build", "-o", "main.exe", "."]
                  working_directory: "."
      - name: Dockerize
        jobs:
          - name: BuildDockerImage
            agent: admin
            tasks:
              - exec:
                  command: docker
                  arguments: ["build", "-t", "my-golang-app", "."]
                  working_directory: "."
              - exec:
                  command: docker
                  arguments: ["tag", "my-golang-app", "hym101/my-golang-app:latest"]
              - exec:
                  command: docker
                  arguments: ["login", "-u", "${DOCKER_USERNAME}", "-p", "${DOCKER_PASSWORD}"]
              - exec:
                  command: docker
                  arguments: ["push", "your-dockerhub-username/my-golang-app:latest"]
