cdformat_version: 3
pipelines:
  My-App-Demo:
    group: myFirstpipeline
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/htetgit/My-App-Demo.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - Build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Compile:
            timeout: 0
            tasks:
            - exec:
                command: go
                run_if: passed
            - exec:
                command: build
                run_if: passed
            - exec:
                command: -o
                run_if: passed
            - exec:
                command: main
                run_if: passed
            - exec:
                command: .
                run_if: passed
